---
- name: Install NFS client packages.
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Create NFS mount directories.
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
  loop: "{{ nfs_mounts }}"

- name: Mount NFS shares.
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: nfs
    opts: "{{ item.opts | default(nfs_default_opts) }}"
    state: mounted
    dump: "0"
    passno: "0"
  loop: "{{ nfs_mounts }}"