---
- name: Restart authentik
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/authentik"
    state: restarted
    recreate: always

- name: Stop authentik
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/authentik"
    state: stopped

- name: Start authentik
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/authentik"
    state: present