---
- name: Deploy External Monitoring (Tailscale + Uptime Kuma)
  hosts: infra_external-monitoring
  become: true

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_role:
        name: common

  roles:
    - tailscale
    - role: docker_service
      vars:
        service_name: uptime-kuma
        service_compose_template: "{{ playbook_dir }}/templates/compose.yaml.j2"
