---
- name: Deploy Time Server (NTP/PTP)
  hosts: time
  become: true
  
  handlers:
    - name: Include various service handlers.
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_tasks: ../common/prereq.yml

  tasks:
    - name: Configure GPS.
      ansible.builtin.include_tasks: tasks/gps.yml

    - name: Configure chrony.
      ansible.builtin.include_tasks: tasks/chrony.yml

    - name: Configure PTP.
      ansible.builtin.include_tasks: tasks/ptp.yml

    - name: Install Kernel.
      ansible.builtin.include_tasks: tasks/kernel.yml