#ENC[AES256_GCM,data:RhJTlbKluR+GBYl9MhPOL1THKXrPITREztH4DIdq1g==,iv:TrVSmwlpg0KWQUr1Wt2GiEJwFR9ecs8/yuJRCShCcBc=,tag:e3aPDaTnFUylXW9pKwQMpw==,type:comment]
homepage_sonarr_key: ENC[AES256_GCM,data:1OkADWyUWoMt3VCkcfL7tB+DrGkZCV8m0+UblguCGYw=,iv:Pp6wgc8FqcYBMqjSzKB7afurzjAMzOzfhSSYll0OiJ4=,tag:1iYjaeVAAVJyJxbIb+DTTg==,type:str]
homepage_radarr_key: ENC[AES256_GCM,data:rcfK4QLMAUUmi6FpHvBI11bb4SuXpaqv9qJkeMG1CjY=,iv:9aIEe6mm7aPIoGt0KR1nQ4+mKUGo5H0EOqb8IjMISmA=,tag:7G+JvgXL9P2MbPNNN0rNew==,type:str]
homepage_bazarr_key: ENC[AES256_GCM,data:F32spk+RHT0YTedNmbrZ+Kfi3HNMLS7n0R/HGYlUBjU=,iv:LE3PwdxkIqeVeSbymPBO2QCy9T2p125yCLlpCVkR0eY=,tag:qINaOc18jHs969Vs/yVQJA==,type:str]
homepage_prowlarr_key: ENC[AES256_GCM,data:tT62LL8i/MIn1Oxlq92zSdTF6qBcDpl504jY1+0vtW8=,iv:pbiarTdowX3Cz06TCHQvPQe6lDfFRTqvUbS8CtfIAwA=,tag:Ue1jlnhfZgZ1QuDZHoWcDA==,type:str]
homepage_sabnzbd_key: ENC[AES256_GCM,data:pf+q/AA7g+mTvjo9RMobEeESvqQ33P859HKuWwNtjfE=,iv:livlAtEk94NR1hBtloqpnv0qbImhCPThZCFsR4MBNsE=,tag:HtydLHtXuWZIiMKMQevKpQ==,type:str]
homepage_plex_key: ENC[AES256_GCM,data:Qw+/o5zbBG6R77Lu8PpROkFHhBE=,iv:mshdm/Zj202TUV/W8iU9N8MhjXOaX2kXdqCvpOu2Tv0=,tag:5x79OIh+MSU6H70L0KrBzg==,type:str]
#ENC[AES256_GCM,data:Re/LKGKTa4hklsI474MjedBt9tuC,iv:svC0P/0jyOirShm0g0trZb32g6euD6YKulLX1MLfe5U=,tag:e9UMULvYpS+faEcLDO6gFw==,type:comment]
grafana_admin_password: ENC[AES256_GCM,data:aRvrh5apqwOv,iv:T5RKZ7QCejoZG/G1+8Uz6JC0LQiXm+OPWWi+fQ8/t/U=,tag:Qvt4d+UotxaqtADoQ6g7PQ==,type:str]
#ENC[AES256_GCM,data:2rD3qILvNQ0q7HsWpe8VpwEaIrgPaQ==,iv:I8IIUDtpAwiUx8u3QaLGKNEJ0QdILGye6/apoaub3bk=,tag:g+yuWlsu7CWCDqUnhQEbwg==,type:comment]
frigate_rtsp_password: ENC[AES256_GCM,data:fZcx24Tift0100uLpQ==,iv:SOXwARNmBJKRmD5NrsNz/vCK11xG+k3KdX0QC+4Tc+o=,tag:0/IOJVHHJnqe+7JOeOXZkw==,type:str]
#ENC[AES256_GCM,data:3IgA15N9NjJR4d+/97WvIQv9rnzAyQA3,iv:GdBb80vOhFzUVfNgaTxCG/xw3nR0I0BJZfdqeHgtiAk=,tag:pcPzkhjug8c3aq+5EYvnrg==,type:comment]
terraria_server_password: ENC[AES256_GCM,data:nU9h,iv:4FKFNfYB6LQSS8gAXWW1akd9zyibaC2kwgndsJJdhCQ=,tag:F+tpjvq2PfTiA2wF29iMjg==,type:str]
#ENC[AES256_GCM,data:XzurXc5MH5T+/g==,iv:hj/TtsGRXfLpxd9J1oYm7dDbl5VPjw7ltcryzVkZ0Xc=,tag:qWk5ZnR2IhHO0UGHx+ItDA==,type:comment]
tailscale_auth_key: ""
#ENC[AES256_GCM,data:SBFUyygAVBU=,iv:94dtXtPFDjbq35QuUyUFBKEG1813Gfa2FpjcqllZDlI=,tag:EZ860NpXmSf9MC3eo7XOvg==,type:comment]
cf_api_token: ENC[AES256_GCM,data:u0I7UoJ+UOpccmDi7M7T9mnDBVKXGROoD0OIUWxltNwPuOXMWAAkjw==,iv:yIfbMcORwbM9smga+Dxv8gNiLrg7IEcC3y6PO7G74yk=,tag:a9rzEzybXnj0ChGFWMQvHA==,type:str]
cf_email: ENC[AES256_GCM,data:dA+j7b9hESpwb6u5SO/tsDxzoF3JZVVJIsIqYw==,iv:ZVK/OGgd0tdwuJSxfMhRePTxtUKG5PLnZ0hQdj9kv+M=,tag:wqPDIi+IIZXQU5WOMCWekg==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdDU1MWN2bUdsSldXQVZV
            YTVQZHBEWHBTbnZKQVZnY2FDWmxIRDVidG44Cjc2S2QwQUJRQmgrK3NQRDVna1E5
            UFpKSUl1OG5rdEVta3ZDcGdTdTFKR00KLS0tIENjcUNzQ2s5b21QdlV5TXN6Nyth
            eWQ2OForQXM0RjhFdE1DWldWaUpPL2sKsO1HyutGoIYXCwPSyWWvBhkunEbga8PZ
            XXv50ZQp+rd8ZyZP0cVm6Wa7Cf0RQIymanuMIDp9C7d946YjVoSg3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T20:25:49Z"
    mac: ENC[AES256_GCM,data:fByLm+pRcyjM/6vEyjUt/jhWCsSf0/fnX/RYqzeQP9s7nLtiJwp+tDq4uhp8Og5ZY7zrl4EKea3nPlSMhUwKfmFq4185L0Wik9t3RUDIMISVdIKJY7THr2abE1BZzXUbOFbkBrgTksLXAeXtpzCqHu/wT+RXuDKqeeKyj48ibLQ=,iv:UaFndlCzOjeyt+rhYyu2adM9er0pr+ICA2g/fYy7j+8=,tag:cjeXBTlMxV125iB1g5VtJw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
