---
# Global variables for WIL environment

# Domains managed by DNS and reverse proxy
domains:
  - name: "5am.video"
  - name: "sfc.al"
system_timezone: America/New_York

# Unified deploy path for all services
deploy_path: /opt
