---
# DNS Forwarders
dns_forwarders:
  - "1.1.1.1"
  - "1.0.0.1"

# Trusted Networks
dns_trusted_networks:
  - localhost
  - localnets
  - 10.2.0.0/16

# Forward Zone A Records
dns_a_records:
  - name: "ns"
    ip: "10.2.20.53"
  - name: "sabnzbd"
    ip: "10.2.20.80"
  - name: "prowlarr"
    ip: "10.2.20.80"
  - name: "sonarr"
    ip: "10.2.20.80"
  - name: "radarr"
    ip: "10.2.20.80"
  - name: "bazarr"
    ip: "10.2.20.80"
  - name: "plex"
    ip: "10.2.20.80"
  - name: "tunarr"
    ip: "10.2.20.80"
  - name: "pulsarr"
    ip: "10.2.20.80"
  - name: "cleanuparr"
    ip: "10.2.20.80"
  - name: "huntarr"
    ip: "10.2.20.80"
  - name: "tdarr"
    ip: "10.2.20.80"
  - name: "frigate"
    ip: "10.2.20.80"
  - name: "truenas"
    ip: "10.2.0.100"
  - name: "caddy"
    ip: "10.2.20.80"

# Reverse Zone PTR Records
dns_ptr_records:
  - octet: "1"
    hostname: "unifi.{{ domain_name }}."
  - octet: "53"
    hostname: "dns.{{ domain_name }}."
  - octet: "123"
    hostname: "time.{{ domain_name }}."