---
# DNS Server (BIND9) configuration

dns_forwarders:
  - "1.1.1.1"
  - "1.0.0.1"

dns_trusted_networks:
  - localhost
  - localnets
  - 10.2.0.0/16

# Reverse Proxy IP (used for DNS A records of proxied services)
reverse_proxy_ip: "10.2.20.80"

# Reverse Zone PTR Records
# Cloudflare DDNS records to keep updated with public IP
ddns_domains:
  - "*.5am.video"
  - "*.wil.5am.cloud"
  - "*.ext.5am.cloud"

# Reverse Zone PTR Records
dns_ptr_records:
  - octet: "1"
    hostname: "unifi.5am.video."
  - octet: "53"
    hostname: "dns.5am.video."
  - octet: "123"
    hostname: "time.5am.video."
