---
- name: Create birdle directory.
  ansible.builtin.file:
    path: "{{ deploy_path }}/birdle"
    state: directory
    owner: "{{ birdle_user }}"
    group: "{{ birdle_group }}"
    mode: "0755"

- name: Deploy docker-compose.yaml.
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ deploy_path }}/birdle/docker-compose.yaml"
    owner: "{{ birdle_user }}"
    group: "{{ birdle_group }}"
    mode: "0644"
  notify:
    - Restart birdle

- name: Pull latest birdle image.
  community.docker.docker_image:
    name: "{{ birdle_image }}"
    source: pull
    force_source: true
  notify:
    - Restart birdle

- name: Ensure birdle is running.
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/birdle"
    state: present
  register: birdle_output
