---
- name: Deploy Birdle
  hosts: app_birdle
  become: true

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_role:
        name: common

  roles:
    - role: docker_service
      vars:
        service_name: birdle
        service_compose_template: "{{ playbook_dir }}/templates/compose.yaml.j2"
        service_user: "{{ birdle_user }}"
        service_group: "{{ birdle_group }}"
        service_images:
          - "{{ birdle_image }}"
