---
# DNS Forwarders
dns_forwarders:
  - "1.1.1.1"
  - "1.0.0.1"

# Trusted Networks
dns_trusted_networks:
  - localhost
  - localnets
  - 10.2.0.0/16
  - 10.1.0.0/16

# Forward Zone A Records
dns_a_records:
  - name: "ns"
    ip: "10.1.30.53"
  - name: "sonarr"
    ip: "10.1.30.100"
  - name: "ca"
    ip: "10.1.30.3"
  - name: "radarr"
    ip: "10.1.30.100"
  - name: "time"
    ip: "10.1.30.123"

# Reverse Zone PTR Records
dns_ptr_records:
  - octet: "1"
    hostname: "unifi.{{ domain_name }}."
  - octet: "53"
    hostname: "dns.{{ domain_name }}."
  - octet: "123"
    hostname: "time.{{ domain_name }}."