#ENC[AES256_GCM,data:5mJjXLv2o+0aHCmj2uOvmteMvK0zpA==,iv:wmTvg2vt9FP2/dpDaqD0xhXWtcagWbsl8W2KYdLZ4n4=,tag:w7afi7Ldu/LJwEkMAT15wg==,type:comment]
frigate_rtsp_password: ENC[AES256_GCM,data:5YDtWgVi15MHTDSCqw==,iv:H0ogI+eYFmwgJAsdp80PGzsX1VOZzcafrS3BQe0uc1g=,tag:3Rm3JEkdJxrX2aKQBqEKtw==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdXg3NU5yanpHOVRIY3ZJ
            cWJ5bGowTkR5YWxWcmNEbko2NUN0U1FidVdJCnR0bGZIbFpKOVhDVWhhSXBSQmxs
            VEFkTjcvUkVPM1Z5bXB1UFlGTy9lazAKLS0tIEUrV014NUxhbUh1RVFDTEY4YXZ1
            ZUJTZk0yQUdlYjdlZ3lmVUNQSUhlUGsKijPedI/kZ1DAMH17+DaymyzsfqL5Ju6O
            vooKjVSO6GQoh0ZynF2tL7VrQfCor8Ji/j7QuOzXTJ5/Iwr5kSa2Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T03:27:47Z"
    mac: ENC[AES256_GCM,data:UgGgvV88y3g7SEnMfhQLoOWbTgHjZWLhy7NdoNt40I9u4Oz1RFEqZPGMFpiFxDUWdajxdPfQXAPvh82SE0oPOhbhWFvCvoof4MhifjbyRitAkh2MzH/v3D3KbmNnNUhgP0Yw7cTyGmY0h7oZoBj8vskIKrRMqYUgf8fYkeL3Aeo=,iv:RcLI5FfGdOdNMxxzzJzib94wUfx1sE66KnaCTvvo/pY=,tag:F5VmEomW8xGbEnPjhOAHfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
