---
- name: Deploy Games Server
  hosts: app_games-server
  become: true

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_role:
        name: common

  roles:
    - role: docker_service
      vars:
        service_name: games-server
        service_compose_template: "{{ playbook_dir }}/templates/docker-compose.yaml.j2"
        service_user: "{{ games_server_user }}"
        service_group: "{{ games_server_group }}"
