#ENC[AES256_GCM,data:kqI04VO9YgpWQ/iSiBYQ2ymSLlZyHpq7,iv:tvTMwx7lgtLvF8sqK8u8wK/AowVVrLiH5ClsBr7PVNQ=,tag:GfIHdpOKmoegotmAF7ttcg==,type:comment]
terraria_server_password: ENC[AES256_GCM,data:FtLw,iv:lMVVoGZ6JzXet0sNllVHzf8FjwkCmlhD9GA3fo/PpyI=,tag:qejUqKEtYHaPEr+lbnc5bA==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VVFXYVl2T0lVWENjYnNM
            a0pFc3R0dENsU0dSVVVsTzJEMVFIMnU1UFdFCnAvYkFIajVzT3hWWXBsWnVYVTU0
            QTMwdHdWZXFiYmxBRlQ4eHJBWVlac0UKLS0tIFRpS21OalUySFM4OGxvbGNJYVNB
            YVF6UFZOV1FzRVp1alpRYzFjR1hzWjQKWdIFAT++5tAbkdS24IgfbeIFXxJrTwX+
            k7dEocHaEarQykjBkiX3QLTtEUcZB4fr7XmF4QtxtaMTNhx9VVxQ2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T03:27:48Z"
    mac: ENC[AES256_GCM,data:OGyq5pdq2BqFg2lBjeeo3KTKD/AF4VxCh6MbM3riNt7cX2KYi0+yWD5e/RETj5rv+xvmf+bdZayAyVsccSPRwM1Ncy8xy8gd+bcJB4yX6Goh39LFYoNeMu+KIuWQj4xC2kjInV5Xguy9aoHfvTVaW2nguWGoYx0X2MXyLKIH+XM=,iv:pb/BSjXizK17q4BRtkGU9vTxAdgz1N9cHWiGJ2FvB2E=,tag:t3l9zW5t35Jg11Ykqa46rQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
