---
- name: Deploy VPS (Tailscale + Uptime Kuma)
  hosts: vps
  become: true

  handlers:
    - name: Include various service handlers.
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_tasks: ../common/prereq.yml

  tasks:
    - name: Install Docker.
      ansible.builtin.include_tasks: tasks/docker.yml

    - name: Configure Tailscale.
      ansible.builtin.include_tasks: tasks/tailscale.yml

    - name: Deploy Uptime Kuma.
      ansible.builtin.include_tasks: tasks/uptime-kuma.yml