---
- name: Deploy Personal Website
  hosts: app_website
  become: true

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_role:
        name: common

  roles:
    - role: docker_service
      vars:
        service_name: website
        service_compose_template: "{{ playbook_dir }}/templates/compose.yaml.j2"
        service_user: "{{ website_user }}"
        service_group: "{{ website_group }}"
        service_images:
          - "{{ website_image }}"
