---
- name: Restart monitoring-stack
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/monitoring"
    state: restarted
    recreate: always

- name: Stop monitoring-stack
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/monitoring"
    state: stopped

- name: Start monitoring-stack
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/monitoring"
    state: present