convertx_jwt_secret: ENC[AES256_GCM,data:i68/slgrD3q+v011LouVx3JUSX9kqn3lNiNYpa6XbAoIweVTtAxdHofBnurCa7XKRdb5z/2UyFkYu7ub2krZsg==,iv:6j6zcQNwN2lcF4KFtZDf+gAxA2Lro2VUlVD0gbRkkMY=,tag:R8X4f170QeJhM069yfiLzw==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOVdxSU5vY0FsbVozeVkv
            MDZFT1NoTTB1aEpkZ2t2MHM5OVFvUXYzV2dRCmdKaXRZOUZUU2dndFp5dU5mZDdJ
            dFdVQ1BKT0gwaXpPdHlDejlabU1kZDgKLS0tIFg3SUFVTEhYTDJUWWVwMTVINWpq
            aE9aTG1DME1iV0Z5cXFSS05qRzhsSjAKEYGho9XOxdEZN2DDTEnH1i0GmCPHeIND
            pHRAWz5EvcOfPwuE2U4wz7hfeJlozZ3ta7vaFOdeAl9IB25YPuPxHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T20:32:57Z"
    mac: ENC[AES256_GCM,data:626vBYSZy/UCuSKDM5LYuyVWQeip/CCsu67/m8P73FOF2TWMopNElAUqU8jzvV50ADNPswAqjxGO9JIPnOJk8yb339PO6QJtUHH3ZO1e0VADNfq/04H4gXkMpCPW5K2pfzRW58Klf/QrHdnNLBthVofTkul5yyWp65zn8Hx5Rxg=,iv:F3B4DUCpg5AAH0mrqRqESIshTjlxUxSy8MY4spcNwYw=,tag:WTwJRDZ9/9XN1EJ3mXVUcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
