---
- name: Deploy External Monitoring (Tailscale + Uptime Kuma)
  hosts: external_monitoring
  become: true

  handlers:
    - name: Include various service handlers.
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: Include common prerequisites.
      ansible.builtin.include_tasks: ../common/prereq.yml

  roles:
    - docker
    - tailscale

  tasks:
    - name: Deploy Uptime Kuma.
      ansible.builtin.include_tasks: tasks/uptime-kuma.yml
