#ENC[AES256_GCM,data:3DSoyfySBGG5ig==,iv:9GRKaafBBkuV6eJ46xnSzyCtU9M7TJJfw5f/WDf7izo=,tag:3lBssgWvk6dW9FcB/psULg==,type:comment]
tailscale_auth_key: ""
#ENC[AES256_GCM,data:LuV0/JdLxxk=,iv:mQauJESsKzbIVn5Ca2CiMek3pqpanjTps1dPd7EvINw=,tag:xOgnjYpcgBoGQG3bbG+oAw==,type:comment]
cf_api_token: ENC[AES256_GCM,data:G7VhWuUjRyYCRHsX5RmvjkQ6sYtPLwrxrVoDNKpT1HLKXR3zkzbCSQ==,iv:8UTku8J77F36XSlFvqgtsOI+hHyAtRsIZL9Y8tkz5xI=,tag:BEQwAc665wvgRTNseK9MjA==,type:str]
cf_email: ENC[AES256_GCM,data:bGmoO1gk0wVcLBW0gbNB6zr9OHW7ICFwDGYkVQ==,iv:pdziwqjvUtAjz4fDZFEkMY17vEm6Qn8bKb/FJeIYYvc=,tag:IuA+g9+MJeAWb4lLyScY3A==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRDIyMDhmbzhOdnJxZEx5
            eVB2TWNKSTNJb0hnM0VlN2U1N0xUSUszWkhBCkI2TW5OTHV1Z0dOWWRxZDZ0OHNj
            RTdCS1F1ZEZXVURGcDYwbFNwSnBHVzgKLS0tIC96WkNNZEJONXBJWWtJL0t2aERN
            RTJOUFluMnlqYzF1a2dMNnFqekVEMlUKAHTY22xEuyvZ/dkUiYGj6xOjvYoX8IBK
            fxD5xR4NyFmd39Z5vQFSMp4jLt67ZIGrXPQYhnbUFlr/mKYAPiJ8xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T03:27:47Z"
    mac: ENC[AES256_GCM,data:nxVAn2YuIEIVfwtYpL/EQwROiM5LtFxmT8DO44ylgPd3Iw28kVRelMGutPiA0rcLtHQsfVqj50JQnxGMBOyH8+tWAlvL4Tm5Zl3T8PlLM5O89cwmsMP1scD+XcCREbT87iIHB0M84N0X8ll/3AS6H12okEfMZ+acqyFZ/Wet9M8=,iv:Dx93cfVCkmZSKDccWBeJXpubPV7oSPxkonfuwvINpGE=,tag:I2xcpvQ37GJB2ZmzYwuUoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
