---
- name: Restart netbootxyz
  community.docker.docker_compose_v2:
    project_src: /opt/netbootxyz
    state: restarted
    recreate: always

- name: Stop netbootxyz
  community.docker.docker_compose_v2:
    project_src: /opt/netbootxyz
    state: stopped

- name: Start netbootxyz
  community.docker.docker_compose_v2:
    project_src: /opt/netbootxyz
    state: present