---
# Global variables for external environment

# Domains managed by DNS and reverse proxy
domains:
  - name: "5am.video"
  - name: "samuel.computer"
system_timezone: America/New_York

# Unified deploy path for all services
deploy_path: /opt
