---
- name: Rebuild caddy
  community.docker.docker_compose_v2:
    project_src: "{{ reverse_proxy_deploy_path }}"
    build: always
    state: present

- name: Restart caddy
  community.docker.docker_compose_v2:
    project_src: "{{ reverse_proxy_deploy_path }}"
    state: restarted
