---
# Monitoring Stack container configuration

# User/group IDs
monitoring_uid: "1000"
monitoring_gid: "1000"
monitoring_user: root
monitoring_group: root

# Container image versions
prometheus_version: "v3.3.0"
grafana_version: "11.6.0"
node_exporter_version: "v1.9.1"
#uptime_kuma_version: "2"
homepage_version: "latest"

# Directories to back up (relative to /opt)
backup_targets:
  - prometheus
  - grafana
  - uptime-kuma
  - homepage
