#ENC[AES256_GCM,data:v4kVE//1DcBGzetPFBRrzOpp9oTshJyfoaVz1vfSbA==,iv:2A9TJoopKyhQMFqfMQmhYLcviwQu48CPNaJFy/xom6I=,tag:HyQkmDfeIqcrf6AoRrVQYA==,type:comment]
homepage_sonarr_key: ENC[AES256_GCM,data:9nrAoDAe70H0tNlRwBL5U+tw5rPYDrGXWti1Jx5zrIw=,iv:BDkW12hFjHGgaP0GDWkjhGGIttYXhgRyCg9Ly/u6ZQI=,tag:dh/YLqONF0dV59cZFfvoOA==,type:str]
homepage_radarr_key: ENC[AES256_GCM,data:ScyWhaFdBkUlKfmyRlLQvtc7vfTVDCYQKGrPqvc8cT8=,iv:u1RepvJcJd/NSmFvbEvhc5Z3RJDqM4eR3uZ2j+hSdww=,tag:FLr4ZbUyZjF3ZWh7GfuTIQ==,type:str]
homepage_bazarr_key: ENC[AES256_GCM,data:xsOgEcHxaW/Hg1WO6fZ2MwvwrkvCKfOYspacX6EmFFA=,iv:t2TGFxIDfCGXbnPFw0832QyztgdD43h9eZco/M0EKgs=,tag:omLxfUIVNPeJaMrxt0MeRQ==,type:str]
homepage_prowlarr_key: ENC[AES256_GCM,data:4dZkXvZpiMaZx09CYegSGVilhNVHEA63WhzKlu5n2kI=,iv:FzdBVr6M9M2+gPo0sB4cK8NqdJEkVcmHXYwy4XzN1So=,tag:Fzu4GVCwsIhZRpJtA7Uyag==,type:str]
homepage_sabnzbd_key: ENC[AES256_GCM,data:vqgU7JFrUBwRRVT2il9El47ex5FX7SqihQtRCBIvG2c=,iv:jh7ETP0wfi7MuhWhLTE97xZvlUEex+2KobmSVjpQUDg=,tag:R9QJu38/ONTN2whTDr+O7g==,type:str]
homepage_plex_key: ENC[AES256_GCM,data:iJnLduMD9yGrF1qIOZidke6Dmo4=,iv:cmIl9jO3DC+d0zDiL7yoVJ8f+VEKpyWadGrWb8VE/y4=,tag:moC9de410NyXbmo912ceeA==,type:str]
#ENC[AES256_GCM,data:JPT9AYMBbDRTEWRzEjQIg2cDmSoJ,iv:DkNGryC4kBe658M9VQgWMjGjHRJvA/34SLcXOracg4k=,tag:y8B7xoS3uWtyQx+W2zn4Aw==,type:comment]
grafana_admin_password: ENC[AES256_GCM,data:AZb9QTyEwKX7,iv:hOO/EUGpm0qooOdeFfkwZljpGHy9Fn1yPKOYwrU7Wqc=,tag:py/sIUCxCXMkdWwGd7dJjw==,type:str]
sops:
    age:
        - recipient: age14kkq0ymnjz35dsu4mq6jvc3ne2n9vxf64aynxne7y6k7kd0ndplqlyu6m8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGT2d6ejZnZWdOUzd4RGov
            anIwc25jRkxMdXRqdHdNM0tRL1VKTmtPeGpZCm5nL1lFa3NTRm43enVodlgySGtH
            L1VhUzdVd0M3S2VTa1U5V0ZqMTFGODQKLS0tIFdwdThWTVpwQjJDV05TdXZ3RFRp
            M2dPTlB0OThzTmZjbG1XQnpoaVFJU2sKGKbi8Aw6JJNlueVsUEYFm2DwPUrM5EMu
            MtVpx/wY6X9d1rmmaD0zcDwC5lsLFuaTRfmMKtmMKGnIUVymV0fjLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T03:27:48Z"
    mac: ENC[AES256_GCM,data:xFtfsxMEDqie4FaF2hik5pBa9C9PTJF6ZF/fEJHyIS06Dhazhbn6xvbGFobZPK+/2qS9aMyNNrW+l1u+7Fyy9jKdAjmtkVlRt7/l4yQf/AIO6KOnzXYOH3lVjf02HXqPurh34i3HxR2mwKw6NuDjIxdrU0Yqtii1QFhaUILJPrc=,iv:FJcy+dGhkLbMD6Ek+ukSM9Ap/IQjvRib/u/S07ssvXY=,tag:AJYim9bOzF4QS145D9gbug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
