---
- name: Restart tailscaled
  ansible.builtin.service:
    name: tailscaled
    state: restarted

- name: Restart uptime-kuma
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/uptime-kuma"
    state: restarted
    recreate: always

- name: Stop uptime-kuma
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/uptime-kuma"
    state: stopped

- name: Start uptime-kuma
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/uptime-kuma"
    state: present