---
- name: Rebuild caddy
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/caddy"
    build: always
    state: present

- name: Restart caddy
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/caddy"
    state: restarted
