---
- name: Restart games-server
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/games-server"
    state: restarted
    recreate: always

- name: Stop games-server
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/games-server"
    state: stopped

- name: Start games-server
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/games-server"
    state: present
