---
- name: Create website directory.
  ansible.builtin.file:
    path: "{{ deploy_path }}/website"
    state: directory
    owner: "{{ website_user }}"
    group: "{{ website_group }}"
    mode: "0755"

- name: Deploy docker-compose.yaml.
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ deploy_path }}/website/docker-compose.yaml"
    owner: "{{ website_user }}"
    group: "{{ website_group }}"
    mode: "0644"
  notify:
    - Restart website

- name: Pull latest website image.
  community.docker.docker_image:
    name: "{{ website_image }}"
    source: pull
    force_source: true
  notify:
    - Restart website

- name: Ensure website is running.
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/website"
    state: present
  register: website_output

- name: Display website status.
  ansible.builtin.debug:
    var: website_output
