---
# DNS Server (BIND9) configuration

dns_forwarders:
  - "1.1.1.1"
  - "1.0.0.1"

dns_trusted_networks:
  - localhost
  - localnets
  - 10.2.0.0/16

# Zones forwarded to external DNS (not resolved locally)
dns_forward_zones:
  - "plex.5am.video"
  - "docs.5am.cloud"

# Reverse Proxy IP (used for DNS A records of proxied services)
reverse_proxy_ip: "10.2.20.80"

# Reverse Zone PTR Records
dns_ptr_records:
  - octet: "1"
    hostname: "unifi.5am.video."
  - octet: "53"
    hostname: "dns.5am.video."
  - octet: "123"
    hostname: "time.5am.video."
